### ISSUE TITLE
Self-Hosted: CustomError: example@gmail.com domain of gmail.com has a blank "forward-email" TXT record

### ISSUE THREAD

**Issue by Firewolf34** [forwardemail/free-email-forwarding#157]
Hello! Sorry to trouble you again, but I've got a weird problem this time. Self-hosted. Ubuntu 14.04

Google is able to contact my self-hosted forward-email SMTP server. However I throw an error in the `ForwardEmail.getForwardingAddresses()` async function.

What I find strange about this is, it seems to work the first time the function is called, but the second time it's called during the execution of the program, it fails! Here's the output:

```
forwardemail@HOSTNAME:~$ authbind node index.js &
[1] 2928
forwardemail@HOSTNAME:~$ fatal: Not a git repository (or any of the parent directories): .git
ℹ  info      { component: 'smtp-server',
  tnx: 'listen',
  host: '::',
  port: 25,
  secure: false,
  protocol: 'SMTP' } { value: '{ app: [Object] }%s Server listening on %s:%s' } '' 'SMTP' '[::]' 25
ℹ  info      { component: 'smtp-server',
  tnx: 'connection',
  cid: 'CID',
  host: '209.45.230.32',
  hostname: 'mail-ot1-f42.google.com' } { value: 'Connection from { app: [Object] }' } 'mail-ot1-f42.google.com'
ℹ  info      { component: 'smtp-server',
  tnx: 'starttls',
  cid: 'CID',
  user: undefined,
  cipher: 'TLS_AES_256_GCM_SHA384' } { value: 'Connection upgraded to TLS using ' } 'TLS_AES_256_GCM_SHA384' {
  app: {
    name: '',
    version: '',
    node: 'v12.8.0',
    hash: undefined,
    environment: 'development',
    hostname: 'HOSTNAME',
    pid: 2928
  }
}

Records:

[
  [ 'v=spf1 a mx include:spf.example.com include:_spf.google.com -all' ],
  [ 'forward-email=example@gmail.com' ]
]

Record:

example@gmail.com

Records:

[
  [
    'globalsign-smime-dv=CDdf+XFHsf2wsf6/Gb8+53gdH31dgcscs1l2BPvqKX8='
  ],
  [ 'v=spf1 redirect=_spf.google.com' ]
]

Record:


✖  error     CustomError: example@gmail.com domain of gmail.com has a blank "forward-email" TXT record
    at ForwardEmail.getForwardingAddresses (/home/forwardemail/forward-email/index.js:944:13)
    at async /home/forwardemail/forward-email/index.js:1035:27 {
  message: 'example@gmail.com domain of gmail.com has a blank "forward-email" TXT record',
  responseCode: 550
} {
  app: {
    name: '',
    version: '',
    node: 'v12.8.0',
    hash: undefined,
    environment: 'development',
    hostname: 'HOSTNAME',
    pid: 2928
  }
}
ℹ  info      { component: 'smtp-server',
  tnx: 'close',
  cid: 'CID',
  host: '209.45.230.32',
  user: undefined } { value: 'Connection closed to { app: [Object] }' } 'mail-ot1-f42.google.com'
```

I have slightly instrumented the function with some `console.log()` so you can see the variable data as it's processed. As you can see, the function is called twice, and the second time it fails. I think this is during a lookup to Google's servers. Here's the function in question with instrumentation:

``` Javascript
  // TODO: we should cache this recursive lookup for 2m or something
  // this returns the forwarding address for a given email address
  async getForwardingAddresses(address, recursive = []) {
    const domain = this.parseDomain(address);
    const records = await dns.resolveTxtAsync(domain);
    console.log("\nRecords:\n");
    console.log(records);

    // dns TXT record must contain `forward-email=` prefix
    const validRecords = [];

    // add support for multi-line TXT records
    for (let i = 0; i < records.length; i++) {
      records[i] = records[i].join(''); // join chunks together
      if (records[i].startsWith(`${this.config.recordPrefix}=`))
        validRecords.push(
          records[i].replace(`${this.config.recordPrefix}=`, '')
        );
    }

    // join multi-line TXT records together and replace double w/single commas
    const record = validRecords
      .join(',')
      .replace(/,+/g, ',')
      .trim();

    console.log("\nRecord:\n");
    console.log(record);
    // if the record was blank then throw an error
    if (s.isBlank(record))
      throw new CustomError(
        `${address} domain of ${domain} has a blank "${this.config.recordPrefix}" TXT record`
      );

    // e.g. hello@niftylettuce.com => niftylettuce@gmail.com
    // record = "forward-email=hello:niftylettuce@gmail.com"
    // e.g. hello+test@niftylettuce.com => niftylettuce+test@gmail.com
    // record = "forward-email=hello:niftylettuce@gmail.com"
    // e.g. *@niftylettuce.com => niftylettuce@gmail.com
    // record = "forward-email=niftylettuce@gmail.com"
    // e.g. *+test@niftylettuce.com => niftylettuce@gmail.com
    // record = "forward-email=niftylettuce@gmail.com"

... SNIP ...
```

And here's my TXT records, which I think I've set up correctly:
![txtrecs](https://user-images.githubusercontent.com/2159739/62727229-98444500-b9de-11e9-8c0e-2861693fd77c.PNG)

**Comment by niftylettuce** [comment]
You running with `NODE_ENV=production`?

**Comment by Firewolf34** [comment]
Oh, I had it on development so that I could see the debug information.

Turning it to production did enable the SSL I think, as I had some SSL-related errors I was able to fix.

But - I think the problem persists, here's the (still instrumented, without my console.logs nothing would appear in stdout) output of the program in production mode:
```
forwardemail@hostname:~$ authbind node index.js
fatal: Not a git repository (or any of the parent directories): .git

Records:

[
  [ 'v=spf1 a mx include:spf.example.com -all' ],
  [ 'forward-email=admin:example@gmail.com' ],
  [ 'forward-email=example@gmail.com' ]
]

Record:

admin:example@gmail.com,example@gmail.com

Records:

[
  [ 'v=spf1 redirect=_spf.google.com' ],
  [
    'globalsign-smime-dv=CDYX+XFHfdsfswml6/Gb8+59BsgdszUr3fd1lsdgvqKX8='
  ]
]

Record:

```

And Google returns the same error: `550 DNS lookup for admin@[my FQDN here] did not return a valid MX record `

So looks like that second call to the function may still be exhibiting the "isBlank" throw. Or maybe another exception entirely. Do you have an Error Log I can send you to detect errors in production mode?

**Comment by niftylettuce** [comment]
I'm going to close this out as a lot has changed since Aug 2019.  I suggest upgrading to latest version and if you still have issues please file another with more details/error logs.
